<?php
/**
 * V3CategoryApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * platform_core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BasalamSDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use BasalamSDK\ApiException;
use BasalamSDK\Configuration;
use BasalamSDK\FormDataProcessor;
use BasalamSDK\HeaderSelector;
use BasalamSDK\ObjectSerializer;

/**
 * V3CategoryApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V3CategoryApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'readCategoriesV3CategoriesGet' => [
            'application/json',
        ],
        'readCategoryAttributeV3CategoriesCategoryIdAttributesGet' => [
            'application/json',
        ],
        'readCategoryV3CategoriesCategoryIdGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation readCategoriesV3CategoriesGet
     *
     * Read Categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoriesV3CategoriesGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BasalamSDK\Model\CategoriesResponse
     */
    public function readCategoriesV3CategoriesGet(string $contentType = self::contentTypes['readCategoriesV3CategoriesGet'][0])
    {
        list($response) = $this->readCategoriesV3CategoriesGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation readCategoriesV3CategoriesGetWithHttpInfo
     *
     * Read Categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoriesV3CategoriesGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BasalamSDK\Model\CategoriesResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function readCategoriesV3CategoriesGetWithHttpInfo(string $contentType = self::contentTypes['readCategoriesV3CategoriesGet'][0])
    {
        $request = $this->readCategoriesV3CategoriesGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\CategoriesResponse',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BasalamSDK\Model\CategoriesResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\CategoriesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation readCategoriesV3CategoriesGetAsync
     *
     * Read Categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoriesV3CategoriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readCategoriesV3CategoriesGetAsync(string $contentType = self::contentTypes['readCategoriesV3CategoriesGet'][0])
    {
        return $this->readCategoriesV3CategoriesGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation readCategoriesV3CategoriesGetAsyncWithHttpInfo
     *
     * Read Categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoriesV3CategoriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readCategoriesV3CategoriesGetAsyncWithHttpInfo(string $contentType = self::contentTypes['readCategoriesV3CategoriesGet'][0])
    {
        $returnType = '\BasalamSDK\Model\CategoriesResponse';
        $request = $this->readCategoriesV3CategoriesGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'readCategoriesV3CategoriesGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoriesV3CategoriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function readCategoriesV3CategoriesGetRequest(string $contentType = self::contentTypes['readCategoriesV3CategoriesGet'][0])
    {


        $resourcePath = '/v3/categories';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation readCategoryAttributeV3CategoriesCategoryIdAttributesGet
     *
     * Read Category Attribute
     *
     * @param  int $category_id category_id (required)
     * @param  int|null $product_id product_id (optional)
     * @param  int|null $vendor_id vendor_id (optional)
     * @param  bool|null $exclude_multi_selects exclude_multi_selects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BasalamSDK\Model\AttributesResponse|\BasalamSDK\Model\HTTPValidationError
     */
    public function readCategoryAttributeV3CategoriesCategoryIdAttributesGet($category_id, $product_id = null, $vendor_id = null, $exclude_multi_selects = null, string $contentType = self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'][0])
    {
        list($response) = $this->readCategoryAttributeV3CategoriesCategoryIdAttributesGetWithHttpInfo($category_id, $product_id, $vendor_id, $exclude_multi_selects, $contentType);
        return $response;
    }

    /**
     * Operation readCategoryAttributeV3CategoriesCategoryIdAttributesGetWithHttpInfo
     *
     * Read Category Attribute
     *
     * @param  int $category_id (required)
     * @param  int|null $product_id (optional)
     * @param  int|null $vendor_id (optional)
     * @param  bool|null $exclude_multi_selects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BasalamSDK\Model\AttributesResponse|\BasalamSDK\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function readCategoryAttributeV3CategoriesCategoryIdAttributesGetWithHttpInfo($category_id, $product_id = null, $vendor_id = null, $exclude_multi_selects = null, string $contentType = self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'][0])
    {
        $request = $this->readCategoryAttributeV3CategoriesCategoryIdAttributesGetRequest($category_id, $product_id, $vendor_id, $exclude_multi_selects, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\AttributesResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BasalamSDK\Model\AttributesResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\AttributesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation readCategoryAttributeV3CategoriesCategoryIdAttributesGetAsync
     *
     * Read Category Attribute
     *
     * @param  int $category_id (required)
     * @param  int|null $product_id (optional)
     * @param  int|null $vendor_id (optional)
     * @param  bool|null $exclude_multi_selects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readCategoryAttributeV3CategoriesCategoryIdAttributesGetAsync($category_id, $product_id = null, $vendor_id = null, $exclude_multi_selects = null, string $contentType = self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'][0])
    {
        return $this->readCategoryAttributeV3CategoriesCategoryIdAttributesGetAsyncWithHttpInfo($category_id, $product_id, $vendor_id, $exclude_multi_selects, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation readCategoryAttributeV3CategoriesCategoryIdAttributesGetAsyncWithHttpInfo
     *
     * Read Category Attribute
     *
     * @param  int $category_id (required)
     * @param  int|null $product_id (optional)
     * @param  int|null $vendor_id (optional)
     * @param  bool|null $exclude_multi_selects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readCategoryAttributeV3CategoriesCategoryIdAttributesGetAsyncWithHttpInfo($category_id, $product_id = null, $vendor_id = null, $exclude_multi_selects = null, string $contentType = self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'][0])
    {
        $returnType = '\BasalamSDK\Model\AttributesResponse';
        $request = $this->readCategoryAttributeV3CategoriesCategoryIdAttributesGetRequest($category_id, $product_id, $vendor_id, $exclude_multi_selects, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'readCategoryAttributeV3CategoriesCategoryIdAttributesGet'
     *
     * @param  int $category_id (required)
     * @param  int|null $product_id (optional)
     * @param  int|null $vendor_id (optional)
     * @param  bool|null $exclude_multi_selects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function readCategoryAttributeV3CategoriesCategoryIdAttributesGetRequest($category_id, $product_id = null, $vendor_id = null, $exclude_multi_selects = null, string $contentType = self::contentTypes['readCategoryAttributeV3CategoriesCategoryIdAttributesGet'][0])
    {

        // verify the required parameter 'category_id' is set
        if ($category_id === null || (is_array($category_id) && count($category_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $category_id when calling readCategoryAttributeV3CategoriesCategoryIdAttributesGet'
            );
        }





        $resourcePath = '/v3/categories/{category_id}/attributes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $product_id,
            'product_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $vendor_id,
            'vendor_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $exclude_multi_selects,
            'exclude_multi_selects', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($category_id !== null) {
            $resourcePath = str_replace(
                '{' . 'category_id' . '}',
                ObjectSerializer::toPathValue($category_id),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $authorization = ["Authorization" => "Bearer " . $this->config->getAccessToken()];

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers,
            $authorization
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation readCategoryV3CategoriesCategoryIdGet
     *
     * Read Category
     *
     * @param  int $category_id category_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryV3CategoriesCategoryIdGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BasalamSDK\Model\CategoryLV12Response|\BasalamSDK\Model\HTTPValidationError
     */
    public function readCategoryV3CategoriesCategoryIdGet($category_id, string $contentType = self::contentTypes['readCategoryV3CategoriesCategoryIdGet'][0])
    {
        list($response) = $this->readCategoryV3CategoriesCategoryIdGetWithHttpInfo($category_id, $contentType);
        return $response;
    }

    /**
     * Operation readCategoryV3CategoriesCategoryIdGetWithHttpInfo
     *
     * Read Category
     *
     * @param  int $category_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryV3CategoriesCategoryIdGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BasalamSDK\Model\CategoryLV12Response|\BasalamSDK\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function readCategoryV3CategoriesCategoryIdGetWithHttpInfo($category_id, string $contentType = self::contentTypes['readCategoryV3CategoriesCategoryIdGet'][0])
    {
        $request = $this->readCategoryV3CategoriesCategoryIdGetRequest($category_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\CategoryLV12Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BasalamSDK\Model\CategoryLV12Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\CategoryLV12Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation readCategoryV3CategoriesCategoryIdGetAsync
     *
     * Read Category
     *
     * @param  int $category_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryV3CategoriesCategoryIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readCategoryV3CategoriesCategoryIdGetAsync($category_id, string $contentType = self::contentTypes['readCategoryV3CategoriesCategoryIdGet'][0])
    {
        return $this->readCategoryV3CategoriesCategoryIdGetAsyncWithHttpInfo($category_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation readCategoryV3CategoriesCategoryIdGetAsyncWithHttpInfo
     *
     * Read Category
     *
     * @param  int $category_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryV3CategoriesCategoryIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readCategoryV3CategoriesCategoryIdGetAsyncWithHttpInfo($category_id, string $contentType = self::contentTypes['readCategoryV3CategoriesCategoryIdGet'][0])
    {
        $returnType = '\BasalamSDK\Model\CategoryLV12Response';
        $request = $this->readCategoryV3CategoriesCategoryIdGetRequest($category_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'readCategoryV3CategoriesCategoryIdGet'
     *
     * @param  int $category_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readCategoryV3CategoriesCategoryIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function readCategoryV3CategoriesCategoryIdGetRequest($category_id, string $contentType = self::contentTypes['readCategoryV3CategoriesCategoryIdGet'][0])
    {

        // verify the required parameter 'category_id' is set
        if ($category_id === null || (is_array($category_id) && count($category_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $category_id when calling readCategoryV3CategoriesCategoryIdGet'
            );
        }


        $resourcePath = '/v3/categories/{category_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($category_id !== null) {
            $resourcePath = str_replace(
                '{' . 'category_id' . '}',
                ObjectSerializer::toPathValue($category_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
