<?php
/**
 * V3ProductApi
 * PHP version 8.1
 *
 * @category Class
 * @package  BasalamSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * basalam
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BasalamSDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use BasalamSDK\ApiException;
use BasalamSDK\Configuration;
use BasalamSDK\FormDataProcessor;
use BasalamSDK\HeaderSelector;
use BasalamSDK\ObjectSerializer;

/**
 * V3ProductApi Class Doc Comment
 *
 * @category Class
 * @package  BasalamSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V3ProductApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'readProductsListV3ProductsGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation readProductsListV3ProductsGet
     *
     * Read Products List
     *
     * @param  mixed[]|null $ids ids (optional)
     * @param  mixed[]|null $vendor_ids vendor_ids (optional)
     * @param  string|null $price price (optional)
     * @param  string|null $product_title product_title (optional)
     * @param  string|null $vendor_title vendor_title (optional)
     * @param  string|null $vendor_mobile vendor_mobile (optional)
     * @param  int|null $category_id category_id (optional)
     * @param  int|null $status status (optional)
     * @param  string|null $created_at created_at (optional)
     * @param  int|null $page page (optional)
     * @param  int|null $per_page per_page (optional)
     * @param  string|null $sort sort (optional)
     * @param  string|null $prefer prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductsListV3ProductsGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed|\BasalamSDK\Model\HTTPValidationError
     */
    public function readProductsListV3ProductsGet($ids = null, $vendor_ids = null, $price = null, $product_title = null, $vendor_title = null, $vendor_mobile = null, $category_id = null, $status = null, $created_at = null, $page = null, $per_page = null, $sort = null, $prefer = null, string $contentType = self::contentTypes['readProductsListV3ProductsGet'][0])
    {
        list($response) = $this->readProductsListV3ProductsGetWithHttpInfo($ids, $vendor_ids, $price, $product_title, $vendor_title, $vendor_mobile, $category_id, $status, $created_at, $page, $per_page, $sort, $prefer, $contentType);
        return $response;
    }

    /**
     * Operation readProductsListV3ProductsGetWithHttpInfo
     *
     * Read Products List
     *
     * @param  mixed[]|null $ids (optional)
     * @param  mixed[]|null $vendor_ids (optional)
     * @param  string|null $price (optional)
     * @param  string|null $product_title (optional)
     * @param  string|null $vendor_title (optional)
     * @param  string|null $vendor_mobile (optional)
     * @param  int|null $category_id (optional)
     * @param  int|null $status (optional)
     * @param  string|null $created_at (optional)
     * @param  int|null $page (optional)
     * @param  int|null $per_page (optional)
     * @param  string|null $sort (optional)
     * @param  string|null $prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductsListV3ProductsGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed|\BasalamSDK\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function readProductsListV3ProductsGetWithHttpInfo($ids = null, $vendor_ids = null, $price = null, $product_title = null, $vendor_title = null, $vendor_mobile = null, $category_id = null, $status = null, $created_at = null, $page = null, $per_page = null, $sort = null, $prefer = null, string $contentType = self::contentTypes['readProductsListV3ProductsGet'][0])
    {
        $request = $this->readProductsListV3ProductsGetRequest($ids, $vendor_ids, $price, $product_title, $vendor_title, $vendor_mobile, $category_id, $status, $created_at, $page, $per_page, $sort, $prefer, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'mixed',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation readProductsListV3ProductsGetAsync
     *
     * Read Products List
     *
     * @param  mixed[]|null $ids (optional)
     * @param  mixed[]|null $vendor_ids (optional)
     * @param  string|null $price (optional)
     * @param  string|null $product_title (optional)
     * @param  string|null $vendor_title (optional)
     * @param  string|null $vendor_mobile (optional)
     * @param  int|null $category_id (optional)
     * @param  int|null $status (optional)
     * @param  string|null $created_at (optional)
     * @param  int|null $page (optional)
     * @param  int|null $per_page (optional)
     * @param  string|null $sort (optional)
     * @param  string|null $prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductsListV3ProductsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readProductsListV3ProductsGetAsync($ids = null, $vendor_ids = null, $price = null, $product_title = null, $vendor_title = null, $vendor_mobile = null, $category_id = null, $status = null, $created_at = null, $page = null, $per_page = null, $sort = null, $prefer = null, string $contentType = self::contentTypes['readProductsListV3ProductsGet'][0])
    {
        return $this->readProductsListV3ProductsGetAsyncWithHttpInfo($ids, $vendor_ids, $price, $product_title, $vendor_title, $vendor_mobile, $category_id, $status, $created_at, $page, $per_page, $sort, $prefer, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation readProductsListV3ProductsGetAsyncWithHttpInfo
     *
     * Read Products List
     *
     * @param  mixed[]|null $ids (optional)
     * @param  mixed[]|null $vendor_ids (optional)
     * @param  string|null $price (optional)
     * @param  string|null $product_title (optional)
     * @param  string|null $vendor_title (optional)
     * @param  string|null $vendor_mobile (optional)
     * @param  int|null $category_id (optional)
     * @param  int|null $status (optional)
     * @param  string|null $created_at (optional)
     * @param  int|null $page (optional)
     * @param  int|null $per_page (optional)
     * @param  string|null $sort (optional)
     * @param  string|null $prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductsListV3ProductsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readProductsListV3ProductsGetAsyncWithHttpInfo($ids = null, $vendor_ids = null, $price = null, $product_title = null, $vendor_title = null, $vendor_mobile = null, $category_id = null, $status = null, $created_at = null, $page = null, $per_page = null, $sort = null, $prefer = null, string $contentType = self::contentTypes['readProductsListV3ProductsGet'][0])
    {
        $returnType = 'mixed';
        $request = $this->readProductsListV3ProductsGetRequest($ids, $vendor_ids, $price, $product_title, $vendor_title, $vendor_mobile, $category_id, $status, $created_at, $page, $per_page, $sort, $prefer, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'readProductsListV3ProductsGet'
     *
     * @param  mixed[]|null $ids (optional)
     * @param  mixed[]|null $vendor_ids (optional)
     * @param  string|null $price (optional)
     * @param  string|null $product_title (optional)
     * @param  string|null $vendor_title (optional)
     * @param  string|null $vendor_mobile (optional)
     * @param  int|null $category_id (optional)
     * @param  int|null $status (optional)
     * @param  string|null $created_at (optional)
     * @param  int|null $page (optional)
     * @param  int|null $per_page (optional)
     * @param  string|null $sort (optional)
     * @param  string|null $prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductsListV3ProductsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function readProductsListV3ProductsGetRequest($ids = null, $vendor_ids = null, $price = null, $product_title = null, $vendor_title = null, $vendor_mobile = null, $category_id = null, $status = null, $created_at = null, $page = null, $per_page = null, $sort = null, $prefer = null, string $contentType = self::contentTypes['readProductsListV3ProductsGet'][0])
    {















        $resourcePath = '/v3/products';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ids,
            'ids', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $vendor_ids,
            'vendor_ids', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $price,
            'price', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $product_title,
            'product_title', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $vendor_title,
            'vendor_title', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $vendor_mobile,
            'vendor_mobile', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $category_id,
            'category_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_at,
            'created_at', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($prefer !== null) {
            $headerParams['prefer'] = ObjectSerializer::toHeaderValue($prefer);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
