<?php
/**
 * V4ProductApi
 * PHP version 8.1
 *
 * @category Class
 * @package  BasalamSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * basalam
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BasalamSDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use BasalamSDK\ApiException;
use BasalamSDK\Configuration;
use BasalamSDK\FormDataProcessor;
use BasalamSDK\HeaderSelector;
use BasalamSDK\ObjectSerializer;

/**
 * V4ProductApi Class Doc Comment
 *
 * @category Class
 * @package  BasalamSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V4ProductApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createProductV4VendorsVendorIdProductsPost' => [
            'application/json',
        ],
        'patchUpdateProductV4ProductsProductIdPatch' => [
            'application/json',
        ],
        'patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch' => [
            'application/json',
        ],
        'readProductV4ProductsProductIdGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createProductV4VendorsVendorIdProductsPost
     *
     * Create Product
     *
     * @param  int $vendor_id vendor_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaCreateProductSchema $api_schemas_v4_product_schema_create_product_schema api_schemas_v4_product_schema_create_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProductV4VendorsVendorIdProductsPost'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BasalamSDK\Model\ReadProductResponse|\BasalamSDK\Model\HTTPValidationError
     */
    public function createProductV4VendorsVendorIdProductsPost($vendor_id, $api_schemas_v4_product_schema_create_product_schema, string $contentType = self::contentTypes['createProductV4VendorsVendorIdProductsPost'][0])
    {
        list($response) = $this->createProductV4VendorsVendorIdProductsPostWithHttpInfo($vendor_id, $api_schemas_v4_product_schema_create_product_schema, $contentType);
        return $response;
    }

    /**
     * Operation createProductV4VendorsVendorIdProductsPostWithHttpInfo
     *
     * Create Product
     *
     * @param  int $vendor_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaCreateProductSchema $api_schemas_v4_product_schema_create_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProductV4VendorsVendorIdProductsPost'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BasalamSDK\Model\ReadProductResponse|\BasalamSDK\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createProductV4VendorsVendorIdProductsPostWithHttpInfo($vendor_id, $api_schemas_v4_product_schema_create_product_schema, string $contentType = self::contentTypes['createProductV4VendorsVendorIdProductsPost'][0])
    {
        $request = $this->createProductV4VendorsVendorIdProductsPostRequest($vendor_id, $api_schemas_v4_product_schema_create_product_schema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\ReadProductResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BasalamSDK\Model\ReadProductResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\ReadProductResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createProductV4VendorsVendorIdProductsPostAsync
     *
     * Create Product
     *
     * @param  int $vendor_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaCreateProductSchema $api_schemas_v4_product_schema_create_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProductV4VendorsVendorIdProductsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProductV4VendorsVendorIdProductsPostAsync($vendor_id, $api_schemas_v4_product_schema_create_product_schema, string $contentType = self::contentTypes['createProductV4VendorsVendorIdProductsPost'][0])
    {
        return $this->createProductV4VendorsVendorIdProductsPostAsyncWithHttpInfo($vendor_id, $api_schemas_v4_product_schema_create_product_schema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createProductV4VendorsVendorIdProductsPostAsyncWithHttpInfo
     *
     * Create Product
     *
     * @param  int $vendor_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaCreateProductSchema $api_schemas_v4_product_schema_create_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProductV4VendorsVendorIdProductsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProductV4VendorsVendorIdProductsPostAsyncWithHttpInfo($vendor_id, $api_schemas_v4_product_schema_create_product_schema, string $contentType = self::contentTypes['createProductV4VendorsVendorIdProductsPost'][0])
    {
        $returnType = '\BasalamSDK\Model\ReadProductResponse';
        $request = $this->createProductV4VendorsVendorIdProductsPostRequest($vendor_id, $api_schemas_v4_product_schema_create_product_schema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createProductV4VendorsVendorIdProductsPost'
     *
     * @param  int $vendor_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaCreateProductSchema $api_schemas_v4_product_schema_create_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createProductV4VendorsVendorIdProductsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createProductV4VendorsVendorIdProductsPostRequest($vendor_id, $api_schemas_v4_product_schema_create_product_schema, string $contentType = self::contentTypes['createProductV4VendorsVendorIdProductsPost'][0])
    {

        // verify the required parameter 'vendor_id' is set
        if ($vendor_id === null || (is_array($vendor_id) && count($vendor_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $vendor_id when calling createProductV4VendorsVendorIdProductsPost'
            );
        }

        // verify the required parameter 'api_schemas_v4_product_schema_create_product_schema' is set
        if ($api_schemas_v4_product_schema_create_product_schema === null || (is_array($api_schemas_v4_product_schema_create_product_schema) && count($api_schemas_v4_product_schema_create_product_schema) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_schemas_v4_product_schema_create_product_schema when calling createProductV4VendorsVendorIdProductsPost'
            );
        }


        $resourcePath = '/v4/vendors/{vendor_id}/products';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($vendor_id !== null) {
            $resourcePath = str_replace(
                '{' . 'vendor_id' . '}',
                ObjectSerializer::toPathValue($vendor_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($api_schemas_v4_product_schema_create_product_schema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($api_schemas_v4_product_schema_create_product_schema));
            } else {
                $httpBody = $api_schemas_v4_product_schema_create_product_schema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchUpdateProductV4ProductsProductIdPatch
     *
     * Patch Update Product
     *
     * @param  int $product_id product_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaPatchUpdateProductSchema $api_schemas_v4_product_schema_patch_update_product_schema api_schemas_v4_product_schema_patch_update_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BasalamSDK\Model\ReadProductResponse|\BasalamSDK\Model\HTTPValidationError
     */
    public function patchUpdateProductV4ProductsProductIdPatch($product_id, $api_schemas_v4_product_schema_patch_update_product_schema, string $contentType = self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'][0])
    {
        list($response) = $this->patchUpdateProductV4ProductsProductIdPatchWithHttpInfo($product_id, $api_schemas_v4_product_schema_patch_update_product_schema, $contentType);
        return $response;
    }

    /**
     * Operation patchUpdateProductV4ProductsProductIdPatchWithHttpInfo
     *
     * Patch Update Product
     *
     * @param  int $product_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaPatchUpdateProductSchema $api_schemas_v4_product_schema_patch_update_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BasalamSDK\Model\ReadProductResponse|\BasalamSDK\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchUpdateProductV4ProductsProductIdPatchWithHttpInfo($product_id, $api_schemas_v4_product_schema_patch_update_product_schema, string $contentType = self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'][0])
    {
        $request = $this->patchUpdateProductV4ProductsProductIdPatchRequest($product_id, $api_schemas_v4_product_schema_patch_update_product_schema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\ReadProductResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BasalamSDK\Model\ReadProductResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\ReadProductResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation patchUpdateProductV4ProductsProductIdPatchAsync
     *
     * Patch Update Product
     *
     * @param  int $product_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaPatchUpdateProductSchema $api_schemas_v4_product_schema_patch_update_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchUpdateProductV4ProductsProductIdPatchAsync($product_id, $api_schemas_v4_product_schema_patch_update_product_schema, string $contentType = self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'][0])
    {
        return $this->patchUpdateProductV4ProductsProductIdPatchAsyncWithHttpInfo($product_id, $api_schemas_v4_product_schema_patch_update_product_schema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchUpdateProductV4ProductsProductIdPatchAsyncWithHttpInfo
     *
     * Patch Update Product
     *
     * @param  int $product_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaPatchUpdateProductSchema $api_schemas_v4_product_schema_patch_update_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchUpdateProductV4ProductsProductIdPatchAsyncWithHttpInfo($product_id, $api_schemas_v4_product_schema_patch_update_product_schema, string $contentType = self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'][0])
    {
        $returnType = '\BasalamSDK\Model\ReadProductResponse';
        $request = $this->patchUpdateProductV4ProductsProductIdPatchRequest($product_id, $api_schemas_v4_product_schema_patch_update_product_schema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchUpdateProductV4ProductsProductIdPatch'
     *
     * @param  int $product_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaPatchUpdateProductSchema $api_schemas_v4_product_schema_patch_update_product_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchUpdateProductV4ProductsProductIdPatchRequest($product_id, $api_schemas_v4_product_schema_patch_update_product_schema, string $contentType = self::contentTypes['patchUpdateProductV4ProductsProductIdPatch'][0])
    {

        // verify the required parameter 'product_id' is set
        if ($product_id === null || (is_array($product_id) && count($product_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_id when calling patchUpdateProductV4ProductsProductIdPatch'
            );
        }

        // verify the required parameter 'api_schemas_v4_product_schema_patch_update_product_schema' is set
        if ($api_schemas_v4_product_schema_patch_update_product_schema === null || (is_array($api_schemas_v4_product_schema_patch_update_product_schema) && count($api_schemas_v4_product_schema_patch_update_product_schema) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_schemas_v4_product_schema_patch_update_product_schema when calling patchUpdateProductV4ProductsProductIdPatch'
            );
        }


        $resourcePath = '/v4/products/{product_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($product_id !== null) {
            $resourcePath = str_replace(
                '{' . 'product_id' . '}',
                ObjectSerializer::toPathValue($product_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($api_schemas_v4_product_schema_patch_update_product_schema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($api_schemas_v4_product_schema_patch_update_product_schema));
            } else {
                $httpBody = $api_schemas_v4_product_schema_patch_update_product_schema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch
     *
     * Patch Update Product Variation
     *
     * @param  int $product_id product_id (required)
     * @param  int $variation_id variation_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaUpdateProductVariantsSchema $api_schemas_v4_product_schema_update_product_variants_schema api_schemas_v4_product_schema_update_product_variants_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BasalamSDK\Model\ReadProductResponse|\BasalamSDK\Model\HTTPValidationError
     */
    public function patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch($product_id, $variation_id, $api_schemas_v4_product_schema_update_product_variants_schema, string $contentType = self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'][0])
    {
        list($response) = $this->patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchWithHttpInfo($product_id, $variation_id, $api_schemas_v4_product_schema_update_product_variants_schema, $contentType);
        return $response;
    }

    /**
     * Operation patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchWithHttpInfo
     *
     * Patch Update Product Variation
     *
     * @param  int $product_id (required)
     * @param  int $variation_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaUpdateProductVariantsSchema $api_schemas_v4_product_schema_update_product_variants_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BasalamSDK\Model\ReadProductResponse|\BasalamSDK\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchWithHttpInfo($product_id, $variation_id, $api_schemas_v4_product_schema_update_product_variants_schema, string $contentType = self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'][0])
    {
        $request = $this->patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchRequest($product_id, $variation_id, $api_schemas_v4_product_schema_update_product_variants_schema, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\ReadProductResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BasalamSDK\Model\ReadProductResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\ReadProductResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchAsync
     *
     * Patch Update Product Variation
     *
     * @param  int $product_id (required)
     * @param  int $variation_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaUpdateProductVariantsSchema $api_schemas_v4_product_schema_update_product_variants_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchAsync($product_id, $variation_id, $api_schemas_v4_product_schema_update_product_variants_schema, string $contentType = self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'][0])
    {
        return $this->patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchAsyncWithHttpInfo($product_id, $variation_id, $api_schemas_v4_product_schema_update_product_variants_schema, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchAsyncWithHttpInfo
     *
     * Patch Update Product Variation
     *
     * @param  int $product_id (required)
     * @param  int $variation_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaUpdateProductVariantsSchema $api_schemas_v4_product_schema_update_product_variants_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchAsyncWithHttpInfo($product_id, $variation_id, $api_schemas_v4_product_schema_update_product_variants_schema, string $contentType = self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'][0])
    {
        $returnType = '\BasalamSDK\Model\ReadProductResponse';
        $request = $this->patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchRequest($product_id, $variation_id, $api_schemas_v4_product_schema_update_product_variants_schema, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'
     *
     * @param  int $product_id (required)
     * @param  int $variation_id (required)
     * @param  \BasalamSDK\Model\ApiSchemasV4ProductSchemaUpdateProductVariantsSchema $api_schemas_v4_product_schema_update_product_variants_schema (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatchRequest($product_id, $variation_id, $api_schemas_v4_product_schema_update_product_variants_schema, string $contentType = self::contentTypes['patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'][0])
    {

        // verify the required parameter 'product_id' is set
        if ($product_id === null || (is_array($product_id) && count($product_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_id when calling patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'
            );
        }

        // verify the required parameter 'variation_id' is set
        if ($variation_id === null || (is_array($variation_id) && count($variation_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $variation_id when calling patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'
            );
        }

        // verify the required parameter 'api_schemas_v4_product_schema_update_product_variants_schema' is set
        if ($api_schemas_v4_product_schema_update_product_variants_schema === null || (is_array($api_schemas_v4_product_schema_update_product_variants_schema) && count($api_schemas_v4_product_schema_update_product_variants_schema) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_schemas_v4_product_schema_update_product_variants_schema when calling patchUpdateProductVariationV4ProductsProductIdVariationsVariationIdPatch'
            );
        }


        $resourcePath = '/v4/products/{product_id}/variations/{variation_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($product_id !== null) {
            $resourcePath = str_replace(
                '{' . 'product_id' . '}',
                ObjectSerializer::toPathValue($product_id),
                $resourcePath
            );
        }
        // path params
        if ($variation_id !== null) {
            $resourcePath = str_replace(
                '{' . 'variation_id' . '}',
                ObjectSerializer::toPathValue($variation_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($api_schemas_v4_product_schema_update_product_variants_schema)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($api_schemas_v4_product_schema_update_product_variants_schema));
            } else {
                $httpBody = $api_schemas_v4_product_schema_update_product_variants_schema;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation readProductV4ProductsProductIdGet
     *
     * Read Product
     *
     * @param  int $product_id product_id (required)
     * @param  string|null $prefer prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductV4ProductsProductIdGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BasalamSDK\Model\ReadProductResponse|\BasalamSDK\Model\HTTPValidationError
     */
    public function readProductV4ProductsProductIdGet($product_id, $prefer = null, string $contentType = self::contentTypes['readProductV4ProductsProductIdGet'][0])
    {
        list($response) = $this->readProductV4ProductsProductIdGetWithHttpInfo($product_id, $prefer, $contentType);
        return $response;
    }

    /**
     * Operation readProductV4ProductsProductIdGetWithHttpInfo
     *
     * Read Product
     *
     * @param  int $product_id (required)
     * @param  string|null $prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductV4ProductsProductIdGet'] to see the possible values for this operation
     *
     * @throws \BasalamSDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BasalamSDK\Model\ReadProductResponse|\BasalamSDK\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function readProductV4ProductsProductIdGetWithHttpInfo($product_id, $prefer = null, string $contentType = self::contentTypes['readProductV4ProductsProductIdGet'][0])
    {
        $request = $this->readProductV4ProductsProductIdGetRequest($product_id, $prefer, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\ReadProductResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\BasalamSDK\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BasalamSDK\Model\ReadProductResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\ReadProductResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BasalamSDK\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation readProductV4ProductsProductIdGetAsync
     *
     * Read Product
     *
     * @param  int $product_id (required)
     * @param  string|null $prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductV4ProductsProductIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readProductV4ProductsProductIdGetAsync($product_id, $prefer = null, string $contentType = self::contentTypes['readProductV4ProductsProductIdGet'][0])
    {
        return $this->readProductV4ProductsProductIdGetAsyncWithHttpInfo($product_id, $prefer, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation readProductV4ProductsProductIdGetAsyncWithHttpInfo
     *
     * Read Product
     *
     * @param  int $product_id (required)
     * @param  string|null $prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductV4ProductsProductIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function readProductV4ProductsProductIdGetAsyncWithHttpInfo($product_id, $prefer = null, string $contentType = self::contentTypes['readProductV4ProductsProductIdGet'][0])
    {
        $returnType = '\BasalamSDK\Model\ReadProductResponse';
        $request = $this->readProductV4ProductsProductIdGetRequest($product_id, $prefer, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'readProductV4ProductsProductIdGet'
     *
     * @param  int $product_id (required)
     * @param  string|null $prefer (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['readProductV4ProductsProductIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function readProductV4ProductsProductIdGetRequest($product_id, $prefer = null, string $contentType = self::contentTypes['readProductV4ProductsProductIdGet'][0])
    {

        // verify the required parameter 'product_id' is set
        if ($product_id === null || (is_array($product_id) && count($product_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_id when calling readProductV4ProductsProductIdGet'
            );
        }



        $resourcePath = '/v4/products/{product_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($prefer !== null) {
            $headerParams['prefer'] = ObjectSerializer::toHeaderValue($prefer);
        }

        // path params
        if ($product_id !== null) {
            $resourcePath = str_replace(
                '{' . 'product_id' . '}',
                ObjectSerializer::toPathValue($product_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
