<?php
/**
 * ProductShippingDataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  BasalamSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * basalam
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BasalamSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProductShippingDataTest Class Doc Comment
 *
 * @category    Class
 * @description ProductShippingData
 * @package     BasalamSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductShippingDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductShippingData"
     */
    public function testProductShippingData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "illegal_for_iran"
     */
    public function testPropertyIllegalForIran()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "illegal_for_same_city"
     */
    public function testPropertyIllegalForSameCity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
